config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  #==================
  # Resources
  #==================
  resources :relations
  resources :likes
  resources :entries
  resources :telephones
  resources :emails
  resources :users

  #==================
  # Api's
  #==================


  get '/users/api/json', to: 'users#api'
  get '/telephones/api/json', to: 'telephones#api'
  get '/relations/api/json', to: 'relations#api'
  get '/likes/api/json', to:'likes#api'
  get '/entries/api/json', to: 'entries#api'
  get '/emails/api/json', to: 'emails#api'

  post '/users/hiden', to:'users#hiden'
  post '/telephones/hiden', to:'telephones#hiden'
  post '/relations/hiden', to:'relations#hiden'
  post '/likes/hiden', to:'likes#hiden'
  post '/entries/hiden', to:'entries#hiden'
  post '/emails/hiden', to:'emails#hiden'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord

	#==================
  	#ASSOCIATIONS
  	#==================
	#belongs_to :user
	#has_many :like

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /entries/api/json
  def api
    entries = []
    entries = Entry.all
    render :json => entries.to_json()

  end

  # POST /entries/hiden

  def hiden
    response = {code: 400, Message:"you can't do that"}
    
    if params[:id_entry].present? && params[:text].present? && params[:date].present? 
      response = {code: 200, Message: "Entry Created"}
    end 

    render :json => response

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:id_entry, :text, :date)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_entry %>
    <%= f.number_field :id_entry %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Id entry</th>
      <th>Text</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.id_entry %></td>
        <td><%= entry.text %></td>
        <td><%= entry.date %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>
<%= link_to 'JSON', entries_api_json_path %> 
<%= link_to 'Main Page', root_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id entry:</strong>
  <%= @entry.id_entry %>
</p>

<p>
  <strong>Text:</strong>
  <%= @entry.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>