config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  #==================
  # Resources
  #==================
  resources :relations
  resources :likes
  resources :entries
  resources :telephones
  resources :emails
  resources :users

  #==================
  # Api's
  #==================


  get '/users/api/json', to: 'users#api'
  get '/telephones/api/json', to: 'telephones#api'
  get '/relations/api/json', to: 'relations#api'
  get '/likes/api/json', to:'likes#api'
  get '/entries/api/json', to: 'entries#api'
  get '/emails/api/json', to: 'emails#api'

  post '/users/hiden', to:'users#hiden'
  post '/telephones/hiden', to:'telephones#hiden'
  post '/relations/hiden', to:'relations#hiden'
  post '/likes/hiden', to:'likes#hiden'
  post '/entries/hiden', to:'entries#hiden'
  post '/emails/hiden', to:'emails#hiden'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  	#==================
  	#ASSOCIATIONS
  	#==================
  	#has_many :entry
	#has_many :email
	#has_many :telephone
	#has_many :relation



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/api/json
  def api
    users = []
    users = User.all
    render :json => users.to_json()

  end

  # POST /users/hiden

  def hiden
    response = {code: 400, Message:"you can't do that"}
    print("Recibido ")

    if params[:id_user].present? && params[:name].present? && params[:surname].present? && params[:date].present?
      print ("Entro por aqui")
      response = {code: 200, Message: "User Created"}
    end 

    render :json => response

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id_user, :name, :surname, :date)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_user %>
    <%= f.number_field :id_user %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id_user %></td>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.date %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'JSON', users_api_json_path %> 
<%= link_to 'Main Page', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @user.id_user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Date:</strong>
  <%= @user.date %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>