config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  #==================
  # Resources
  #==================
  resources :relations
  resources :likes
  resources :entries
  resources :telephones
  resources :emails
  resources :users

  #==================
  # Api's
  #==================


  get '/users/api/json', to: 'users#api'
  get '/telephones/api/json', to: 'telephones#api'
  get '/relations/api/json', to: 'relations#api'
  get '/likes/api/json', to:'likes#api'
  get '/entries/api/json', to: 'entries#api'
  get '/emails/api/json', to: 'emails#api'

  post '/users/hiden', to:'users#hiden'
  post '/telephones/hiden', to:'telephones#hiden'
  post '/relations/hiden', to:'relations#hiden'
  post '/likes/hiden', to:'likes#hiden'
  post '/entries/hiden', to:'entries#hiden'
  post '/emails/hiden', to:'emails#hiden'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/index.html.erb
<h1>Konrad Social</h1>

<h3>Options</h3>

<table>
  <thead>
    <tr>
      <th>List of User</th>
      <th>List of Emails</th>
      <th>List of Telephones</th>
      <th>List of Relations</th>
      <th>List of Entries</th>
      <th>List of Likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td><%= link_to 'Users', users_path %></td>
        <td><%= link_to 'Emails', emails_path %></td>
        <td><%= link_to 'Telephones', telephones_path %></td>
        <td><%= link_to 'Relations', relations_path %></td>
        <td><%= link_to 'Entries', entries_path %></td>
        <td><%= link_to 'Likes', likes_path %></td>
      </tr>

  </tbody>
</table>

<br>