config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  #==================
  # Resources
  #==================
  resources :relations
  resources :likes
  resources :entries
  resources :telephones
  resources :emails
  resources :users

  #==================
  # Api's
  #==================


  get '/users/api/json', to: 'users#api'
  get '/telephones/api/json', to: 'telephones#api'
  get '/relations/api/json', to: 'relations#api'
  get '/likes/api/json', to:'likes#api'
  get '/entries/api/json', to: 'entries#api'
  get '/emails/api/json', to: 'emails#api'

  post '/users/hiden', to:'users#hiden'
  post '/telephones/hiden', to:'telephones#hiden'
  post '/relations/hiden', to:'relations#hiden'
  post '/likes/hiden', to:'likes#hiden'
  post '/entries/hiden', to:'entries#hiden'
  post '/emails/hiden', to:'emails#hiden'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/telephone.rb
class Telephone < ApplicationRecord

	#==================
  	#ASSOCIATIONS
  	#==================
	#belongs_to :user

end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  before_action :set_telephone, only: [:show, :edit, :update, :destroy]

  # GET /telephones
  # GET /telephones.json
  def index
    @telephones = Telephone.all
  end

  # GET /telephones/1
  # GET /telephones/1.json
  def show
  end

  # GET /telephones/new
  def new
    @telephone = Telephone.new
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to @telephone, notice: 'Telephone was successfully created.' }
        format.json { render :show, status: :created, location: @telephone }
      else
        format.html { render :new }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telephones/1
  # PATCH/PUT /telephones/1.json
  def update
    respond_to do |format|
      if @telephone.update(telephone_params)
        format.html { redirect_to @telephone, notice: 'Telephone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telephone }
      else
        format.html { render :edit }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone.destroy
    respond_to do |format|
      format.html { redirect_to telephones_url, notice: 'Telephone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /telephones/api/json
  def api
    telephones = []
    telephones = Telephone.all
    render :json => telephones.to_json()

  end

  # POST /telephones/hiden

  def hiden
    response = {code: 400, Message:"you can't do that"}
    
    if params[:id_telephone].present? && params[:number].present?
      response = {code: 200, Message: "Telephone Created"}
    end 

    render :json => response

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telephone_params
      params.require(:telephone).permit(:id_telephone, :number)
    end
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/telephones/_form.html.erb
<%= form_for(telephone) do |f| %>
  <% if telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telephone.errors.count, "error") %> prohibited this telephone from being saved:</h2>

      <ul>
      <% telephone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_telephone %>
    <%= f.number_field :id_telephone %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/telephones/edit.html.erb
<h1>Editing Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Show', @telephone %> |
<%= link_to 'Back', telephones_path %>

app/views/telephones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telephones</h1>

<table>
  <thead>
    <tr>
      <th>Id telephone</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.id_telephone %></td>
        <td><%= telephone.number %></td>
        <td><%= link_to 'Show', telephone %></td>
        <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
        <td><%= link_to 'Destroy', telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telephone', new_telephone_path %>
<%= link_to 'JSON', telephones_api_json_path %> 
<%= link_to 'Main Page', root_path %>

app/views/telephones/new.html.erb
<h1>New Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Back', telephones_path %>

app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id telephone:</strong>
  <%= @telephone.id_telephone %>
</p>

<p>
  <strong>Number:</strong>
  <%= @telephone.number %>
</p>

<%= link_to 'Edit', edit_telephone_path(@telephone) %> |
<%= link_to 'Back', telephones_path %>